/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class HolographicMemorySystem {
  constructor(dimensions: number, storagePath?: string | undefined | null, config?: HmsConfigJs | undefined | null)
  get vectorCount(): number
  get nsgTrained(): boolean
  get ivfTrained(): boolean
  get dimensions(): number
  indexStatus(): IndexStatus
  storageHealth(): StorageHealth
  hardwareCapabilities(): HardwareCapabilities
  explainQuery(text: string, k: number): QueryExplanation
  maintainIndices(): Promise<IndexStatus>
  flush(): Promise<void>
  analyzeText(text: string): Promise<TextMetrics>
  calculateReadability(metrics: TextMetrics): Promise<number>
  memorizeText(id: string, text: string, traceId?: string | undefined | null): Promise<void>
  /**
   * Zero-copy text ingestion from a Node.js Buffer. Avoids the UTF-8 copy
   * that occurs with String parameters by reading bytes in-place.
   */
  memorizeTextBuffer(id: string, text: Buffer, traceId?: string | undefined | null): Promise<void>
  /**
   * Batch memorize multiple id/text pairs in a single native call.
   * Uses rayon for parallel encoding, then inserts sequentially.
   */
  memorizeBatch(items: Array<MemorizeBatchItem>, traceId?: string | undefined | null): Promise<void>
  /**
   * Read a file directly from disk via memory-mapping and memorize its content.
   * Avoids passing file content through the JS string boundary entirely.
   */
  memorizeFile(id: string, filePath: string): Promise<void>
  memorizeVector(id: string, vector: Float32Array): Promise<void>
  memorizeScalar(id: string, value: number, min: number, max: number): Promise<void>
  query(text: string, k: number, traceId?: string | undefined | null): Promise<Array<RetrievalResult>>
  /** Converts float32→sparse EntangledHVec on JS thread, then queries on background. */
  queryVector(vector: Float32Array, k: number): Promise<Array<RetrievalResult>>
  queryScalar(value: number, min: number, max: number, k: number): Promise<Array<RetrievalResult>>
  /** Process multiple text queries in parallel, returning results for each. */
  queryBatch(texts: Array<string>, k: number): Promise<Array<Array<RetrievalResult>>>
  /** Process multiple float32 vector queries in parallel. */
  queryVectorBatch(vectors: Array<Float32Array>, k: number): Promise<Array<Array<RetrievalResult>>>
  analyzeComponents(text: string): Promise<Array<RetrievalResult>>
  factorizeDiffusion(productText: string, domains: Array<Array<string>>, maxIter: number): Promise<Array<string | undefined | null>>
  memorizeTriplet(id: string, head: string, relation: string, tail: string): Promise<void>
  queryTriplet(head: string, relation: string, k: number): Promise<Array<RetrievalResult>>
  /**
   * Finds an analogy: A is to B as C is to ?.
   *
   * NOTE: Currently uses character trigram encoding, which has limited semantic
   * understanding. Complex semantic analogies may require higher-level word
   * embeddings (slated for future upgrade).
   */
  findAnalogy(a: string, b: string, c: string, k?: number | undefined | null, traceId?: string | undefined | null): Promise<Array<RetrievalResult>>
  synthesizeConcepts(): Promise<Array<ConceptCandidate>>
  memorizeSequence(id: string, sequence: Array<string>): Promise<void>
  trainNsg(): Promise<void>
  trainIvf(): Promise<void>
  querySequence(partial: Array<string>, k: number): Promise<Array<RetrievalResult>>
  delete(id: string): Promise<boolean>
  compact(): Promise<void>
  auditSince(timestampMs: number): Promise<Array<AuditEntryJs>>
  /**
   * Bundle multiple text items into a single hypervector.
   * Respects the PrivacyConfig: when dp_enabled, uses epsilon-DP noise.
   */
  bundleTexts(texts: Array<string>): Promise<Array<number>>
  memorizeMeaning(id: string, text: string): Promise<void>
  structuralQuery(knownSubjects: Array<string>, knownRelations: Array<string>, targetRole: string): Promise<Array<StructuralResultJs>>
  multiHopQuery(startEntity: string, relations: Array<string>): Promise<Array<MultiHopResultJs>>
  meaningCleanup(text: string): Promise<CleanupResultJs | null>
  cleanupVector(vector: Float32Array): Promise<CleanupResultJs | null>
  declareCompositionRule(name: string, inputRelations: Array<string>, outputRelation: string): void
  get meaningEnabled(): boolean
  startCognition(): void
  stopCognition(): void
  get cognitionRunning(): boolean
  get cognitionCycleCount(): number
  get cognitionInsightCount(): number
  get cognitionEnabled(): boolean
  runCognitionOnce(): number
  governMemory(): GovernanceReportJs
  addGoal(name: string, description: string, relevance: number, urgency: number, cost: number): number | null
  deactivateGoal(name: string): boolean
  activeGoals(): Array<GoalJs>
  planGoal(goal: string, causalRelations: Array<string>, maxDepth?: number | undefined | null): PlanJs
  generateQuestions(): Array<QuestionJs>
  proposeRule(name: string, inputRelations: Array<string>, outputRelation: string, reason: string): number | null
  approveProposal(id: number): boolean
  rejectProposal(id: number): boolean
  get pendingProposals(): number
  get goalCount(): number
  get activeGoalCount(): number
  addRelation(sourceId: string, relationType: string, targetId: string, properties?: string | undefined | null, validFrom?: number | undefined | null, validTo?: number | undefined | null): Promise<void>
  removeRelation(sourceId: string, relationType: string, targetId: string): Promise<boolean>
  declareRelationType(name: string, transitive?: boolean | undefined | null, symmetric?: boolean | undefined | null): void
  traverse(startId: string, relationType?: string | undefined | null, maxDepth?: number | undefined | null, atTime?: number | undefined | null): Promise<Array<GraphPath>>
  outgoingRelations(sourceId: string, relationType?: string | undefined | null, atTime?: number | undefined | null): Promise<Array<Relation>>
  incomingRelations(targetId: string, relationType?: string | undefined | null, atTime?: number | undefined | null): Promise<Array<Relation>>
  get relationCount(): number
  federatedQuery(peerPaths: Array<string>, text: string, k: number): Promise<Array<RetrievalResult>>
}

export interface AuditEntryJs {
  timestampMs: number
  op: string
  idHash: string
  signed: boolean
}

export interface CleanupResultJs {
  id: string
  confidence: number
}

export interface ConceptCandidate {
  centroidId: string
  memberCount: number
  coherence: number
  memberIds: Array<string>
  /** Whether centroid refinement converged (zero reassignments in last pass). */
  stable: boolean
}

export interface GoalJs {
  name: string
  utility: number
}

export interface GovernanceReportJs {
  compositesMerged: number
  compositesForgotten: number
  atomsForgotten: number
  idfRefreshed: boolean
  atomsRefined: number
}

/** Result of a graph traversal or path query. */
export interface GraphPath {
  hops: Array<PathHop>
  /** Product of similarities along the path. */
  score: number
}

/** Runtime CPU capabilities relevant to future dense and sparse kernels. */
export interface HardwareCapabilities {
  architecture: string
  avx2: boolean
  avx512F: boolean
  neon: boolean
  sparseIntersectionKernel: string
}

export interface HmsConfigJs {
  nsgMaxDegree?: number
  nsgEfConstruction?: number
  nsgAutoThreshold?: number
  ivfEnabled?: boolean
  ivfNClusters?: number
  ivfNLandmarks?: number
  ivfDReduced?: number
  ivfNProbe?: number
  ivfAutoThreshold?: number
  shardEnabled?: boolean
  shardCount?: number
  shardAutoThreshold?: number
  shardTargetSize?: number
  componentSimilarityThreshold?: number
  componentMaxNeighbors?: number
  conceptSimilarityThreshold?: number
  conceptMinClusterSize?: number
  diffusionSteps?: number
  diffusionSigmaMax?: number
  diffusionSigmaMin?: number
  diffusionStepSize?: number
  diffusionNLangevin?: number
  signingEnabled?: boolean
  signingKeyPath?: string
  encryptionEnabled?: boolean
  encryptionPassphrase?: string
  encryptionPassphraseEnv?: string
  auditEnabled?: boolean
  dpEnabled?: boolean
  dpEpsilon?: number
  meaningEnabled?: boolean
  meaningBeta?: number
  meaningMaxFanout?: number
  meaningAutoDecompose?: boolean
  meaningMaxHopDepth?: number
  cognitionEnabled?: boolean
  cognitionIntervalSecs?: number
  cognitionMinPatternFreq?: number
  cognitionMinAbstractionMembers?: number
  cognitionMinHypothesisConfidence?: number
}

/** Current index lifecycle state and the next recommended maintenance action. */
export interface IndexStatus {
  vectorCount: number
  nsgTrained: boolean
  ivfTrained: boolean
  nsgTrainingRecommended: boolean
  ivfTrainingRecommended: boolean
  recommendation: string
}

/** Input item for batch memorization — a single id/text pair. */
export interface MemorizeBatchItem {
  id: string
  text: string
}

export interface MultiHopResultJs {
  entityId: string
  confidence: number
  method: string
}

/** A single hop in a graph traversal path. */
export interface PathHop {
  nodeId: string
  relationType: string
  similarity: number
}

export interface PlanJs {
  goal: string
  actions: Array<PlannedActionJs>
  complete: boolean
  totalCost: number
}

export interface PlannedActionJs {
  subject: string
  relation: string
  object: string
  depth: number
  cost: number
}

/** Explains which retrieval strategy HMS would use for a query. */
export interface QueryExplanation {
  route: string
  vectorCount: number
  queryNonzeroDimensions: number
  requestedResults: number
  efSearch: number
  nProbe: number
  nsgAvailable: boolean
  ivfAvailable: boolean
  rationale: string
}

export interface QuestionJs {
  text: string
  goalRelevance: number
}

/** An explicit directed relation between two entities. */
export interface Relation {
  sourceId: string
  relationType: string
  targetId: string
  properties?: string
  /** Milliseconds since epoch. 0 = unbounded. */
  validFrom: number
  /** Milliseconds since epoch. 0 = unbounded (still active). */
  validTo: number
}

/** Declares a relation type with inference semantics. */
export interface RelationType {
  name: string
  /** If true, A->B and B->C implies A->C. */
  transitive: boolean
  /** If true, A->B implies B->A. */
  symmetric: boolean
}

export interface RetrievalResult {
  id: string
  similarity: number
}

/** Persistence health information suitable for diagnostics and monitoring. */
export interface StorageHealth {
  formatVersion: number
  segmentCount: number
  usedBytes: number
  capacityBytes: number
}

export interface StructuralResultJs {
  entityId: string
  confidence: number
  path: string
}

export interface TextMetrics {
  wordCount: number
  sentenceCount: number
  syllableCount: number
  vowelCount: number
  consonantCount: number
  punctuationCount: number
}
