/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface HmsConfigJs {
  nsgMaxDegree?: number;
  nsgEfConstruction?: number;
  nsgAutoThreshold?: number;
  ivfEnabled?: boolean;
  ivfNClusters?: number;
  ivfNLandmarks?: number;
  ivfDReduced?: number;
  ivfNProbe?: number;
  ivfAutoThreshold?: number;
  shardEnabled?: boolean;
  shardCount?: number;
  shardAutoThreshold?: number;
  shardTargetSize?: number;
  conceptSimilarityThreshold?: number;
  conceptMinClusterSize?: number;
  diffusionSteps?: number;
  diffusionSigmaMax?: number;
  diffusionSigmaMin?: number;
  diffusionStepSize?: number;
  diffusionNLangevin?: number;
  signingEnabled?: boolean;
  signingKeyPath?: string;
  encryptionEnabled?: boolean;
  encryptionPassphrase?: string;
  auditEnabled?: boolean;
  dpEnabled?: boolean;
  dpEpsilon?: number;
  meaningEnabled?: boolean;
  meaningBeta?: number;
  meaningMaxFanout?: number;
  meaningAutoDecompose?: boolean;
  meaningMaxHopDepth?: number;
  cognitionEnabled?: boolean;
  cognitionIntervalSecs?: number;
  cognitionMinPatternFreq?: number;
  cognitionMinAbstractionMembers?: number;
  cognitionMinHypothesisConfidence?: number;
}
export interface TextMetrics {
  wordCount: number;
  sentenceCount: number;
  syllableCount: number;
  vowelCount: number;
  consonantCount: number;
  punctuationCount: number;
}
export interface RetrievalResult {
  id: string;
  similarity: number;
}
export interface ConceptCandidate {
  centroidId: string;
  memberCount: number;
  coherence: number;
  memberIds: Array<string>;
}
export interface MemorizeBatchItem {
  id: string;
  text: string;
}
export interface AuditEntryJs {
  timestampMs: number;
  op: string;
  idHash: string;
  signed: boolean;
}
export interface StructuralResultJs {
  entityId: string;
  confidence: number;
  path: string;
}
export interface MultiHopResultJs {
  entityId: string;
  confidence: number;
  method: string;
}
export interface CleanupResultJs {
  id: string;
  confidence: number;
}
export interface GovernanceReportJs {
  compositesMerged: number;
  compositesForgotten: number;
  atomsForgotten: number;
  idfRefreshed: boolean;
  atomsRefined: number;
}
export interface GoalJs {
  name: string;
  utility: number;
}
export interface PlannedActionJs {
  subject: string;
  relation: string;
  object: string;
  depth: number;
}
export interface PlanJs {
  goal: string;
  actions: Array<PlannedActionJs>;
  complete: boolean;
}
export interface QuestionJs {
  text: string;
  goalRelevance: number;
}
export interface GraphPath {
  nodes: Array<string>;
  relations: Array<string>;
  totalSimilarity: number;
  inferred: boolean;
}
export interface Relation {
  sourceId: string;
  relationType: string;
  targetId: string;
  properties?: string;
  validFrom: number;
  validTo: number;
}
export declare class HolographicMemorySystem {
  constructor(
    dimensions: number,
    storagePath?: string | undefined | null,
    config?: HmsConfigJs | undefined | null,
  );
  get vectorCount(): number;
  get nsgTrained(): boolean;
  get ivfTrained(): boolean;
  get dimensions(): number;
  analyzeText(text: string): Promise<TextMetrics>;
  calculateReadability(metrics: TextMetrics): Promise<number>;
  memorizeText(
    id: string,
    text: string,
    traceId?: string | undefined | null,
  ): Promise<void>;
  memorizeTextBuffer(
    id: string,
    text: Buffer,
    traceId?: string | undefined | null,
  ): Promise<void>;
  memorizeBatch(
    items: Array<MemorizeBatchItem>,
    traceId?: string | undefined | null,
  ): Promise<void>;
  memorizeFile(id: string, filePath: string): Promise<void>;
  memorizeVector(id: string, vector: Float32Array): Promise<void>;
  memorizeScalar(
    id: string,
    value: number,
    min: number,
    max: number,
  ): Promise<void>;
  query(
    text: string,
    k: number,
    traceId?: string | undefined | null,
  ): Promise<Array<RetrievalResult>>;
  queryVector(vector: Float32Array, k: number): Promise<Array<RetrievalResult>>;
  queryScalar(
    value: number,
    min: number,
    max: number,
    k: number,
  ): Promise<Array<RetrievalResult>>;
  queryBatch(
    texts: Array<string>,
    k: number,
  ): Promise<Array<Array<RetrievalResult>>>;
  queryVectorBatch(
    vectors: Array<Float32Array>,
    k: number,
  ): Promise<Array<Array<RetrievalResult>>>;
  analyzeComponents(text: string): Promise<Array<RetrievalResult>>;
  factorizeDiffusion(
    productText: string,
    domains: Array<Array<string>>,
    maxIter: number,
  ): Promise<Array<string | null>>;
  memorizeTriplet(
    id: string,
    head: string,
    relation: string,
    tail: string,
  ): Promise<void>;
  queryTriplet(
    head: string,
    relation: string,
    k: number,
  ): Promise<Array<RetrievalResult>>;
  findAnalogy(
    a: string,
    b: string,
    c: string,
    k?: number | undefined | null,
    traceId?: string | undefined | null,
  ): Promise<Array<RetrievalResult>>;
  synthesizeConcepts(): Promise<Array<ConceptCandidate>>;
  memorizeSequence(id: string, sequence: Array<string>): Promise<void>;
  trainNsg(): Promise<void>;
  trainIvf(): Promise<void>;
  querySequence(
    partial: Array<string>,
    k: number,
  ): Promise<Array<RetrievalResult>>;
  delete(id: string): Promise<boolean>;
  compact(): Promise<void>;
  auditSince(timestampMs: number): Promise<Array<AuditEntryJs>>;
  bundleTexts(texts: Array<string>): Promise<Array<number>>;

  // Meaning Memory API
  memorizeMeaning(id: string, text: string): Promise<void>;
  structuralQuery(
    knownSubjects: Array<string>,
    knownRelations: Array<string>,
    targetRole: string,
  ): Promise<Array<StructuralResultJs>>;
  multiHopQuery(
    startEntity: string,
    relations: Array<string>,
  ): Promise<Array<MultiHopResultJs>>;
  meaningCleanup(text: string): Promise<CleanupResultJs | null>;
  cleanupVector(vector: Float32Array): Promise<CleanupResultJs | null>;
  declareCompositionRule(
    name: string,
    inputRelations: Array<string>,
    outputRelation: string,
  ): void;
  get meaningEnabled(): boolean;

  // Cognition API
  startCognition(): void;
  stopCognition(): void;
  get cognitionRunning(): boolean;
  get cognitionCycleCount(): number;
  get cognitionInsightCount(): number;
  get cognitionEnabled(): boolean;
  runCognitionOnce(): number;
  governMemory(): GovernanceReportJs;

  // Agency API
  addGoal(
    name: string,
    description: string,
    relevance: number,
    urgency: number,
    cost: number,
  ): number | null;
  deactivateGoal(name: string): boolean;
  activeGoals(): Array<GoalJs>;
  planGoal(
    goal: string,
    causalRelations: Array<string>,
    maxDepth?: number | undefined | null,
  ): PlanJs;
  generateQuestions(): Array<QuestionJs>;
  proposeRule(
    name: string,
    inputRelations: Array<string>,
    outputRelation: string,
    reason: string,
  ): number | null;
  approveProposal(id: number): boolean;
  rejectProposal(id: number): boolean;
  get pendingProposals(): number;
  get goalCount(): number;
  get activeGoalCount(): number;

  // Graph API
  addRelation(
    sourceId: string,
    relationType: string,
    targetId: string,
    properties?: string | undefined | null,
    validFrom?: number | undefined | null,
    validTo?: number | undefined | null,
  ): Promise<void>;
  removeRelation(
    sourceId: string,
    relationType: string,
    targetId: string,
  ): Promise<boolean>;
  declareRelationType(
    name: string,
    transitive?: boolean | undefined | null,
    symmetric?: boolean | undefined | null,
  ): void;
  traverse(
    startId: string,
    relationType?: string | undefined | null,
    maxDepth?: number | undefined | null,
    atTime?: number | undefined | null,
  ): Promise<Array<GraphPath>>;
  outgoingRelations(
    sourceId: string,
    relationType?: string | undefined | null,
    atTime?: number | undefined | null,
  ): Promise<Array<Relation>>;
  incomingRelations(
    targetId: string,
    relationType?: string | undefined | null,
    atTime?: number | undefined | null,
  ): Promise<Array<Relation>>;
  get relationCount(): number;
  federatedQuery(
    peerPaths: Array<string>,
    text: string,
    k: number,
  ): Promise<Array<RetrievalResult>>;
}
