// Copyright 2024-2026 WritersLogic Contributors
// SPDX-License-Identifier: Apache-2.0

pub(crate) mod admission;
pub mod agency;
pub mod algebra;
pub(crate) mod atom_memory;
pub(crate) mod audit;
pub mod block_codes;
pub mod bloom_memory;
pub mod cls_memory;
pub mod cognition;
pub mod compose;
pub(crate) mod composite_memory;
pub(crate) mod config;
pub(crate) mod decompose;
pub(crate) mod diffusion;
pub mod encoding;
pub mod engine;
pub mod entangled;
pub(crate) mod error;
pub(crate) mod graph;
pub mod hopfield;
pub(crate) mod idf;
pub(crate) mod index;
pub(crate) mod indexed_memory;
pub mod intersection;
pub(crate) mod ivf;
pub(crate) mod nsg;
pub(crate) mod posting;
#[cfg(feature = "provenance")]
pub mod provenance;
pub mod resonator;
pub(crate) mod role;
pub(crate) mod rules;
pub(crate) mod security;
pub mod sparse_autoencoder;
pub(crate) mod storage;
pub mod ternary;
pub(crate) mod text;
pub(crate) mod tombstone;
pub(crate) mod triple_store;
pub(crate) mod types;

pub use config::HmsConfig;
pub use engine::HmsCore;
