// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PathHop } from "./PathHop";

/**
 * Result of a graph traversal or path query.
 */
export type GraphPath = { hops: Array<PathHop>, 
/**
 * Product of similarities along the path.
 */
score: number, };
