// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Runtime CPU capabilities relevant to future dense and sparse kernels.
 */
export type HardwareCapabilities = { architecture: string, avx2: boolean, avx512f: boolean, neon: boolean, sparseIntersectionKernel: string, };
