// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HmsError = { "type": "InvalidParam", "message": { details: string, } } | { "type": "StorageFailure", "message": { context: string, } } | { "type": "EncodingFailure", "message": { context: string, } } | { "type": "QueryFailure", "message": { context: string, } } | { "type": "IndexNotTrained", "message": { index_type: string, } } | { "type": "CapacityExceeded", "message": { limit: string, } } | { "type": "Internal", "message": { code: number, context: string, } };
