// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Current index lifecycle state and the next recommended maintenance action.
 */
export type IndexStatus = { vectorCount: number, nsgTrained: boolean, ivfTrained: boolean, nsgTrainingRecommended: boolean, ivfTrainingRecommended: boolean, recommendation: string, };
