// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input item for batch memorization — a single id/text pair.
 */
export type MemorizeBatchItem = { id: string, text: string, };
