// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single hop in a graph traversal path.
 */
export type PathHop = { nodeId: string, relationType: string, similarity: number, };
