// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Explains which retrieval strategy HMS would use for a query.
 */
export type QueryExplanation = { route: string, vectorCount: number, queryNonzeroDimensions: number, requestedResults: number, efSearch: number, nProbe: number, nsgAvailable: boolean, ivfAvailable: boolean, rationale: string, };
