// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An explicit directed relation between two entities.
 */
export type Relation = { sourceId: string, relationType: string, targetId: string, properties: string | null, 
/**
 * Milliseconds since epoch. 0 = unbounded.
 */
validFrom: number, 
/**
 * Milliseconds since epoch. 0 = unbounded (still active).
 */
validTo: number, };
