// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Declares a relation type with inference semantics.
 */
export type RelationType = { name: string, 
/**
 * If true, A->B and B->C implies A->C.
 */
transitive: boolean, 
/**
 * If true, A->B implies B->A.
 */
symmetric: boolean, };
