// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Persistence health information suitable for diagnostics and monitoring.
 */
export type StorageHealth = { formatVersion: number, segmentCount: number, usedBytes: number, capacityBytes: number, };
